"""Static research pipeline descriptions — methodology text, not results."""

STAGES = [
    {
        "id": "ecg_input",
        "title": "ECG Input",
        "does": "Accepts a single-lead (or selected-lead) digital ECG time series with sampling rate.",
        "input": "Voltage samples vs time (CSV / synthetic demo / future WFDB).",
        "output": "Raw discrete-time signal x[n] and fs.",
        "algorithm": "File parse or replay buffer. No clinical acquisition hardware is implemented.",
        "reason": "ECG is the measured input; this project does not replace ECG machines.",
        "limitations": "Lead placement, calibration, and analogue front-end are out of scope.",
    },
    {
        "id": "quality",
        "title": "Signal Quality Assessment",
        "does": "Computes heuristic quality flags (flatline, clipping, implausible beat rate, high-frequency noise).",
        "input": "Raw or cleaned ECG plus detected peaks.",
        "output": "Score in [0,1] and qualitative label (acceptable / marginal / poor).",
        "algorithm": "Rule-based SQI analogue; not a certified commercial SQI.",
        "reason": "Poor quality should block over-confident forecasting language.",
        "limitations": "Heuristics can mis-flag ectopy as noise and vice versa.",
    },
    {
        "id": "preprocess",
        "title": "Preprocessing",
        "does": "Removes baseline wander and limits bandwidth; optional mains notch; optional z-normalisation.",
        "input": "Raw ECG, fs, documented cut-offs.",
        "output": "Conditioned ECG.",
        "algorithm": "Zero-phase Butterworth band-pass (0.5–40 Hz default) and IIR notch at 50 Hz when enabled.",
        "reason": "Stabilises subsequent QRS detection and features.",
        "limitations": "Filtering can distort ST/T morphology; not a diagnostic ECG filter set.",
    },
    {
        "id": "rpeak",
        "title": "R-Peak Detection",
        "does": "Estimates QRS (R) locations.",
        "input": "Conditioned ECG.",
        "output": "Sample indices and times of candidate R peaks.",
        "algorithm": "Pan–Tompkins-style band-pass, derivative, squaring, moving integration, peak find.",
        "reason": "RR and many morphological features require beat fiducials.",
        "limitations": "Missed/extra detections in noise, VT/VF, or unusual morphology.",
    },
    {
        "id": "rr",
        "title": "RR / HR / HRV Features",
        "does": "Computes intervals and simple time-domain variability descriptors.",
        "input": "R-peak times.",
        "output": "RR series, mean/median RR, SDNN-like, RMSSD-like, HR.",
        "algorithm": "Differences of peak times; standard statistical summaries.",
        "reason": "Temporal rate dynamics are candidate precursors in some ventricular-arrhythmia literature — as hypotheses, not facts.",
        "limitations": "Not a clinical HRV report; ectopy contaminates NN statistics.",
    },
    {
        "id": "morph",
        "title": "Morphological Features",
        "does": "Summarises QRS width/amplitude and beat-to-beat template variability.",
        "input": "Windows around R peaks.",
        "output": "QRS width heuristic, amplitudes, morphology std.",
        "algorithm": "Fixed windows and envelope thresholding.",
        "reason": "Wide-complex patterns are relevant to ventricular ectopy/VT characterisation.",
        "limitations": "Not 12-lead QRS duration; T-wave/QT omitted unless a validated detector exists.",
    },
    {
        "id": "baseline",
        "title": "Patient-Specific Baseline",
        "does": "Learns feature means/stds from an explicit past window only.",
        "input": "ECG restricted to [t0, t1].",
        "output": "Baseline vector and statistics.",
        "algorithm": "Sliding subwindows; nan-aware mean/std. No future samples.",
        "reason": "Supports the research question on individual electrical characteristics.",
        "limitations": "Requires sufficient clean baseline ECG; residual non-stationarity remains.",
    },
    {
        "id": "twin",
        "title": "Cardiac Digital Twin (computational)",
        "does": "Forms a state vector from selected features plus deviation from baseline.",
        "input": "Current features and optional baseline.",
        "output": "State, deviation, optional RMS z-score.",
        "algorithm": "Deterministic mapping; not a PDE heart model.",
        "reason": "Compact patient-specific representation for temporal modelling.",
        "limitations": "Not anatomical, not a physiological replica, not a clinical digital twin.",
    },
    {
        "id": "sequence",
        "title": "Temporal State Sequence",
        "does": "Stores successive twin states along the recording.",
        "input": "States at times t_k.",
        "output": "Trajectory for visualisation and sequence models.",
        "algorithm": "Hopping analysis windows.",
        "reason": "Forecasting uses history, not a single snapshot.",
        "limitations": "Window length is an experimental choice.",
    },
    {
        "id": "temporal_ai",
        "title": "Temporal AI / Baseline ML",
        "does": "Maps observation-window features to experimental P(event in horizon).",
        "input": "Labelled windows from annotated records only.",
        "output": "Model object and, after evaluation, metrics.",
        "algorithm": "Logistic regression, random forest, gradient boosting; LSTM/GRU/TCN optional when trained.",
        "reason": "Allows comparison of simple vs temporal models without a fake pretrained medical AI.",
        "limitations": "Untrained models produce no scores. Patient-level split is required for honest tests.",
    },
    {
        "id": "forecast",
        "title": "Risk / State Forecast",
        "does": "Reports model score and evidence status for a chosen horizon H.",
        "input": "Features on [t−obs, t) only; labels from events in (t, t+H].",
        "output": "Experimental estimate + ground truth when annotations exist.",
        "algorithm": "Supervised labels from event times; no 'VT will occur' language.",
        "reason": "Core research question on short-term ventricular-tachyarrhythmia-related risk states.",
        "limitations": "H is experimental. Arrhythmias may lack precursors. Not a diagnosis.",
    },
]
