"""Synthetic ECG generation for research demonstration.

This is NOT a clinical recording. Waveforms are constructed from a documented
sum-of-Gaussians PQRST model (inspired by McSharry et al., 2003 dynamical ECG
model morphology, implemented here as a static beat template plus RR modulation).
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np


@dataclass(frozen=True)
class SyntheticRecordMeta:
    record_id: str
    dataset: str
    source: str
    purpose: str
    sampling_rate: float
    duration_seconds: float
    lead: str
    synthetic: bool = True
    disclaimer: str = "Synthetic demonstration data — not a clinical recording."


def _gaussian(t: np.ndarray, mu: float, sigma: float, amp: float) -> np.ndarray:
    return amp * np.exp(-0.5 * ((t - mu) / sigma) ** 2)


def pqrst_template(t_rel: np.ndarray, wide_qrs: bool = False) -> np.ndarray:
    """Unit-beat morphology on relative time in seconds around the R peak."""
    qrs_sigma = 0.018 if wide_qrs else 0.008
    q_amp = -0.18 if not wide_qrs else -0.12
    r_amp = 1.15 if not wide_qrs else 0.85
    s_amp = -0.22 if not wide_qrs else -0.35
    return (
        _gaussian(t_rel, -0.20, 0.025, 0.12)
        + _gaussian(t_rel, -0.035, 0.008, q_amp)
        + _gaussian(t_rel, 0.0, qrs_sigma, r_amp)
        + _gaussian(t_rel, 0.025, 0.010, s_amp)
        + _gaussian(t_rel, 0.22, 0.050, 0.28)
    )


def generate_synthetic_ecg(
    duration_s: float = 180.0,
    fs: float = 250.0,
    mean_hr_bpm: float = 72.0,
    seed: int = 7,
    insert_vt_at_s: float | None = 120.0,
    vt_duration_s: float = 18.0,
) -> tuple[np.ndarray, np.ndarray, dict]:
    """Return (signal, time, annotation_payload).

    If insert_vt_at_s is set, a high-rate wide-QRS episode is inserted as a
    labelled *synthetic* ventricular-tachyarrhythmia-like segment for forecasting
    experiments. This is a demonstration construct, not a clinical VT recording.
    """
    rng = np.random.default_rng(seed)
    n = int(duration_s * fs)
    t = np.arange(n) / fs
    signal = np.zeros(n, dtype=np.float64)

    rr_mean = 60.0 / mean_hr_bpm
    annotations: list[dict] = []
    r_times: list[float] = []

    current = 0.8
    while current < duration_s - 0.4:
        in_vt = (
            insert_vt_at_s is not None
            and insert_vt_at_s <= current < insert_vt_at_s + vt_duration_s
        )
        if in_vt:
            rr = 0.32 + rng.normal(0, 0.012)
            wide = True
        else:
            rr = rr_mean + rng.normal(0, 0.035)
            # occasional isolated wide beat (ectopy-like demonstration morphology)
            wide = bool(rng.random() < 0.015)
        rr = float(np.clip(rr, 0.28, 1.4))
        r_times.append(current)
        beat_start = max(0, int((current - 0.35) * fs))
        beat_end = min(n, int((current + 0.45) * fs))
        t_rel = t[beat_start:beat_end] - current
        signal[beat_start:beat_end] += pqrst_template(t_rel, wide_qrs=wide)
        if wide and not in_vt:
            annotations.append(
                {
                    "event_type": "pvc_like_synthetic",
                    "start_time": current - 0.08,
                    "end_time": current + 0.12,
                    "annotation_source": "synthetic_generator",
                }
            )
        current += rr

    if insert_vt_at_s is not None:
        annotations.append(
            {
                "event_type": "vt",
                "start_time": insert_vt_at_s,
                "end_time": insert_vt_at_s + vt_duration_s,
                "annotation_source": "synthetic_generator",
            }
        )

    # baseline wander + EMG-like noise (demonstration)
    wander = 0.08 * np.sin(2 * np.pi * 0.33 * t)
    emg = 0.012 * rng.normal(size=n)
    mains = 0.008 * np.sin(2 * np.pi * 50.0 * t)
    signal = signal + wander + emg + mains

    meta = {
        "record_id": "SYNTH-DEMO-001",
        "dataset": "Internal synthetic PQRST demonstration set",
        "source": "Generated by generate_synthetic_ecg(); morphology inspired by McSharry et al. 2003",
        "purpose": "Research demonstration",
        "sampling_rate": fs,
        "duration_seconds": duration_s,
        "lead": "synthetic_II",
        "synthetic": True,
        "disclaimer": "Synthetic demonstration data — not a clinical recording.",
        "r_peak_times_s": r_times,
        "annotations": annotations,
    }
    return signal.astype(np.float64), t, meta
